package fr.sewatech.university.model;

// Generated 14 janv. 2015 19:02:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "university")
public class Student implements java.io.Serializable {

	private Integer studentId;
	private String nom;
	private String prenom;
	private int niveau;
	private String specialisation;
	private Set<Course> courses = new HashSet<Course>(0);

	public Student() {
	}

	public Student(String nom, int niveau, String specialisation) {
		this.nom = nom;
		this.niveau = niveau;
		this.specialisation = specialisation;
	}

	public Student(String nom, String prenom, int niveau,
			String specialisation, Set<Course> courses) {
		this.nom = nom;
		this.prenom = prenom;
		this.niveau = niveau;
		this.specialisation = specialisation;
		this.courses = courses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "student_id", unique = true, nullable = false)
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@Column(name = "nom", nullable = false, length = 25)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 25)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "niveau", nullable = false)
	public int getNiveau() {
		return this.niveau;
	}

	public void setNiveau(int niveau) {
		this.niveau = niveau;
	}

	@Column(name = "specialisation", nullable = false, length = 25)
	public String getSpecialisation() {
		return this.specialisation;
	}

	public void setSpecialisation(String specialisation) {
		this.specialisation = specialisation;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

}
