package fr.sewatech.university.model;

// Generated 14 janv. 2015 19:02:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "university")
public class Teacher implements java.io.Serializable {

	private int teacherId;
	private String nom;
	private String prenom;
	private String grade;
	private String specialite;
	private Set<Course> courses = new HashSet<Course>(0);

	public Teacher() {
	}

	public Teacher(int teacherId, String nom) {
		this.teacherId = teacherId;
		this.nom = nom;
	}

	public Teacher(int teacherId, String nom, String prenom, String grade,
			String specialite, Set<Course> courses) {
		this.teacherId = teacherId;
		this.nom = nom;
		this.prenom = prenom;
		this.grade = grade;
		this.specialite = specialite;
		this.courses = courses;
	}

	@Id
	@Column(name = "teacher_id", unique = true, nullable = false)
	public int getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}

	@Column(name = "nom", nullable = false, length = 25)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 25)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "grade", length = 10)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "specialite", length = 25)
	public String getSpecialite() {
		return this.specialite;
	}

	public void setSpecialite(String specialite) {
		this.specialite = specialite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

}
